version: '3.7'

services:
    dev:
        build:
            context: .
        working_dir: /app
        volumes:
            - "..:/app"
#        depends_on:
#            - db_instance
        command: >
            bash -c "pwsh /app/dev/init.ps1 && sleep infinity"
    
    db_instance:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=8y2xQG^tG!wsgPN5B2C!gCEzPn^1w
        ports:
            - 7600:1433

        # image: ghcr.io/dah-dah-demos/solid-tribble-db:dev # 2021.06.22.19-dev